name: Render Diagrams and Generate VisualSolutions.md

on:
  push:
    branches:
      - main
    paths:
      - 'Leetcode/Documentation/diagrams/**/*.puml'
      - 'Leetcode/Documentation/flowcharts/**/*.md'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACTION_TOKEN }}

      - name: Install Mermaid CLI locally
        run: |
          mkdir -p mermaid-cli-local
          cd mermaid-cli-local
          npm init -y
          npm install @mermaid-js/mermaid-cli@10.4.0

      - name: Detect modified Mermaid and PlantUML files
        id: detect_changes
        run: |
          # Mermaid detection
          MERMAID_CANDIDATES=$(git diff --name-only --diff-filter=AM HEAD~1 HEAD 2>/dev/null || git diff-tree --no-commit-id --name-only -r HEAD)
          MODIFIED_MERMAID=$(echo "$MERMAID_CANDIDATES" | grep '^Leetcode/Documentation/flowcharts/.*\.md$' || true)
          echo "MODIFIED_MERMAID=$MODIFIED_MERMAID" >> $GITHUB_ENV
          echo "Detected Mermaid files: $MODIFIED_MERMAID"

          # PlantUML detection
          PUML_CANDIDATES=$(git diff --name-only --diff-filter=AM HEAD~1 HEAD 2>/dev/null || git diff-tree --no-commit-id --name-only -r HEAD)
          MODIFIED_PUML=$(echo "$PUML_CANDIDATES" | grep '^Leetcode/Documentation/diagrams/.*\.puml$' || true)
          echo "MODIFIED_PUML=$MODIFIED_PUML" >> $GITHUB_ENV
          echo "Detected PlantUML files: $MODIFIED_PUML"

      - name: Render Mermaid diagrams to PNG and SVG
        run: |
          echo '{ "args": ["--no-sandbox"] }' > puppeteer-config.json

          for file in $MODIFIED_MERMAID; do
            [ -f "$file" ] || continue
            out_dir=$(dirname "$file")
            base_name=$(basename "$file" .md)
            echo "Rendering $file → $out_dir/$base_name.(png|svg)"

            ./mermaid-cli-local/node_modules/.bin/mmdc -p puppeteer-config.json \
              -i "$file" -o "$out_dir/${base_name}.png"

            ./mermaid-cli-local/node_modules/.bin/mmdc -p puppeteer-config.json \
              -i "$file" -o "$out_dir/${base_name}.svg"
          done

          rm puppeteer-config.json

      - name: Render PlantUML diagrams to SVG
        run: |
          for file in $MODIFIED_PUML; do
            [ -f "$file" ] || continue
            echo "Rendering $file"
            docker run --rm -v "$PWD":/workspace plantuml/plantuml -tsvg "/workspace/$file"
          done

      - name: Auto-generate VisualSolutions.md
        run: |
          output="Leetcode/Documentation/VisualSolutions.md"
          echo "" > "$output"
          for problem_dir in Leetcode/Documentation/flowcharts/*; do
            problem_name=$(basename "$problem_dir")
            echo "## $problem_name – Strategy Comparison" >> "$output"
            echo "" >> "$output"
            for md_file in "$problem_dir"/*.md; do
              base_name=$(basename "$md_file" .md)
              title=$(echo "$base_name" | sed 's/Solution//; s/On//; s/\([A-Z]\)/ \1/g' | sed 's/^ *//')
              echo "### $title" >> "$output"
              echo "![${title}](./flowcharts/${problem_name}/${base_name}.png)" >> "$output"
              echo "" >> "$output"
            done
            echo "---" >> "$output"
            echo "" >> "$output"
          done

      - name: Commit rendered diagrams and VisualSolutions.md
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add Leetcode/Documentation/flowcharts/**/*.png
          git add Leetcode/Documentation/flowcharts/**/*.svg
          git add Leetcode/Documentation/VisualSolutions.md

          if [ -z "$MODIFIED_MERMAID" ] && [ -z "$MODIFIED_PUML" ]; then
            echo "No diagram changes detected. Skipping commit."
            exit 0
          fi

          msg="Autorendered diagrams for updated flowcharts and diagrams"
          git diff --cached --quiet || (
            git commit -m "$msg" &&
            git push https://x-access-token:${GH_TOKEN}@github.com/abhimanyu-builds/Leetcode.git HEAD:main
          )